[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "justice-platform-backend"
version = "0.1.0"
description = "Core API service for the reinvented automated legal discovery platform."
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "Justice Platform Engineering"}]
dependencies = [
  "fastapi>=0.111.0",
  "uvicorn[standard]>=0.29.0",
  "pydantic-settings>=2.2.1"
]

[project.optional-dependencies]
dev = [
  "pytest>=8.2.0",
  "httpx>=0.27.0"
]

[project.scripts]
justice-platform-backend = "justice_platform.main:main"

[tool.pytest.ini_options]
testpaths = ["../../tests/backend"]
addopts = "-q"
filterwarnings = [
  "ignore::DeprecationWarning"
]
