image:
  repository: ghcr.io/discovery/backend
  tag: v0.1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

env:
  - name: PREFECT_API_URL
    value: "https://prefect.discovery.local/api"
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: discovery-database
        key: url

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: api.discovery.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: discovery-tls
      hosts:
        - api.discovery.local
