replicaCount: 1
image:
  repository: ghcr.io/discovery/backend
  tag: v0.1.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi
env:
  - name: PREFECT_API_URL
    value: "https://prefect.dev.discovery.local/api"
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: discovery-database
        key: url
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: api.dev.discovery.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: discovery-dev-tls
      hosts:
        - api.dev.discovery.local
