namespace:
  name: discovery-dev
  labels:
    environment: dev

global:
  otel:
    resourceAttributes:
      deployment.environment: dev
  prometheus:
    interval: 15s

backend:
  replicaCount: 1
  image:
    tag: v0.1.0-dev
  env:
    - name: PREFECT_API_URL
      value: "https://prefect.dev.discovery.local/api"
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: discovery-database
          key: url
  ingress:
    hosts:
      - host: api.dev.discovery.local
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: discovery-dev-tls
        hosts:
          - api.dev.discovery.local
  telemetry:
    serviceMonitor:
      interval: 15s

worker:
  replicaCount: 1
  env:
    - name: PREFECT_API_URL
      value: "https://prefect.dev.discovery.local/api"
    - name: PREFECT_WORK_QUEUE
      value: discovery-dev
    - name: PREFECT_LOGGING_LEVEL
      value: DEBUG
  service:
    enabled: false

frontend:
  replicaCount: 1
  image:
    tag: v0.1.0-dev
  ingress:
    hosts:
      - host: app.dev.discovery.local
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: discovery-frontend-dev-tls
        hosts:
          - app.dev.discovery.local

argocd:
  project:
    destinations:
      - namespace: discovery-dev
        server: https://kubernetes.default.svc
  applications:
    - name: discovery-platform-dev
      repoURL: "https://github.com/example/discovery.git"
      path: infra/helm/platform
      targetRevision: develop
      destinationNamespace: discovery-dev
      valueFiles:
        - values-dev.yaml
      sync:
        prune: true
        selfHeal: true
